<a href="https://colab.research.google.com/github/Arka1212/Data-Science-Assignments/blob/main/NumPy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Reference Code.
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [6]:
# Code.
print(f'Datatype of list_ is {type(list_)}')                  # List datatype.
print(f'Datatype of array_list is {type(array_list)}')        # Array datatype

Datatype of list_ is <class 'list'>
Datatype of array_list is <class 'numpy.ndarray'>


# Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [8]:
# Code.
for l in list_:
  print(type(l))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [9]:
# Code.
for j in array_list:
  print(type(j))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


# Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

# Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.


In [11]:
# Code.
array_list = np.array(object = list_, dtype = int)

In [13]:
# Code.
for val in list_:
  print(type(val))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [16]:
# Code.
for n in array_list:
  print(type(n))            # Datatype is changed from string to int.

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


# Consider the below code to answer further questions:

import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

# Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [18]:
# Code
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [22]:
# Code.
print(num_array)

# Shape of array.
print(f'Shape of num_array is {num_array.shape}')

# Size of array.
print(f'Size of num_array is {num_array.size}')

[[1 2 3]
 [4 5 6]]
Shape of num_array is (2, 3)
Size of num_array is 6


# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [27]:
# Code.
zero_array = np.zeros([3,3])
zero_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [31]:
# Code.
identity = np.eye(5,5)
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])